"""cycle4_template_module

Revision ID: 0007_cycle4_template
Revises: 0006_sprint1_content_model
Create Date: 2026-04-17 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0007_cycle4_template'
down_revision = '0006_sprint1_content_model'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_grade'), 'templates', ['grade'], unique=False)
    op.create_index(op.f('ix_templates_is_public'), 'templates', ['is_public'], unique=False)
    op.create_index(op.f('ix_templates_subject'), 'templates', ['subject'], unique=False)
    op.create_index(op.f('ix_templates_template_type'), 'templates', ['template_type'], unique=False)

    op.create_table('template_sections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_hints', sa.Text(), nullable=True),
    sa.Column('schema_constraints', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_sections_template_id'), 'template_sections', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_sections_template_id'), table_name='template_sections')
    op.drop_table('template_sections')
    op.drop_index(op.f('ix_templates_template_type'), table_name='templates')
    op.drop_index(op.f('ix_templates_subject'), table_name='templates')
    op.create_index(op.f('ix_templates_is_public'), table_name='templates')
    op.drop_index(op.f('ix_templates_grade'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
